### ISSUE TITLE
RuntimeError: PaDEL-Descriptor encountered an error: GLib-GIO-Message: 08:11:00.494: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

### ISSUE THREAD

**Issue by highdxy** [ECRL/PaDELPy#10]
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
python 3.7
I met the errors as following, when i run python test.py (padelpy/tests)

E
======================================================================
ERROR: test_from_smiles (__main__.TestAll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abc/miniconda3/lib/python3.7/site-packages/padelpy/functions.py", line 59, in from_smiles
    sp_timeout=timeout
  File "/home/abc/miniconda3/lib/python3.7/site-packages/padelpy/wrapper.py", line 148, in padeldescriptor
    err.decode('utf-8')
RuntimeError: PaDEL-Descriptor encountered an error: GLib-GIO-Message: 08:11:00.494: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 11, in test_from_smiles
    descriptors = from_smiles('CCC')
  File "/home/abc/miniconda3/lib/python3.7/site-packages/padelpy/functions.py", line 68, in from_smiles
    raise RuntimeError(exception)
RuntimeError: PaDEL-Descriptor encountered an error: GLib-GIO-Message: 08:11:00.494: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

----------------------------------------------------------------------
Ran 1 test in 13.542s

FAILED (errors=1)

**Comment by tjkessler** [comment]
@highdxy - it looks like this stems from an issue on your machine, likely an issue of miniconda installing its own version of glib:

https://askubuntu.com/questions/916334/ubuntu-16-04-glib-gio-message-using-the-memory-gsettings-backend-your-settin/959346

https://askubuntu.com/questions/558446/my-dconf-gsettings-installation-is-broken-how-can-i-fix-it-without-ubuntu-reins

I do not believe this is an issue with PaDELPy, all our unit tests are run in a fresh environment using a recent image of Ubuntu: https://dev.azure.com/uml-ecrl/package-management/_build/results?buildId=25&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9

**Comment by highdxy** [comment]
@tjkessler 
Thanks for your reply. I have solved this issue by following your advice.
