### ISSUE TITLE
Problem when calculate descriptors from smiles by using csv

### ISSUE THREAD

**Issue by sophiameerkat** [ECRL/PaDELPy#11]
I have seen an issue (when calculate descriptors from smiles, an error occured. #9) with related problem; however, when I use the code mentioned in the issue: 

```python
from padelpy import from_smiles
with open('all_smi.csv', 'rt') as f:
	smi = f.readlines()
```

I will get error: IndexError: list index out of range. I have checked for my csv, and when I use the csv provided in that issue, it still get the same problem. How can I fix it?
My environment is Mac OS, and the python version is 3.7.3
Thanks.

**Comment by tjkessler** [comment]
Hi @sophiameerkat,

I apologize for the very late response! Could you provide the full stack trace for the error, as well as the CSV file you used?

Thanks,
Travis

**Comment by tjkessler** [comment]
@sophiameerkat,

Another user encountered an IndexError for a specific compound (https://github.com/ECRL/PaDELPy/issues/12). Does this stack trace look similar to yours?

> Traceback (most recent call last):
> 
> File "C:\Users\Daniel\OneDrive\UCPH\Research\Scripts\PaDEL\PaDEL Descriptors.py", line 3, in
> from_smiles('Oc7ccc5c1c7O[C@H]3[C@]6(OC)C@HC@@(C)C(C)(C)C', timeout=60, output_csv='Buprenorphine.csv')
> 
> File "C:\Users\Daniel\anaconda3\lib\site-packages\padelpy\functions.py", line 81, in from_smiles
> del rows[0]['Name']
> 
> IndexError: list index out of range

I'm looking forward to hearing back from you!

Travis

**Comment by tjkessler** [comment]
I'm going to go ahead and close this issue due to inactivity. If your problem persists, feel free to open it again.
