### ISSUE TITLE
Enabling multithreading

### ISSUE THREAD

**Issue by katasanirohith** [ECRL/PaDELPy#15]
I have seen that padel descriptor allows multi processing([link](http://www.yapcwsoft.com/dd/padeldescriptor/#:~:text=Enter%20a%20value%20(greater%20than%200),the%20number%20of%20cpu%20cores%20available.)). Can we do this in wrapper? because I can see my CPUs are not being used to fullest extent. But, while using GUI from PaDEL usage of CPUs is maximum.

**Comment by tjkessler** [comment]
Hi @katasanirohith,

I believe that multiprocessing is already available for use in PaDELPy. As PaDEL's command line interface is leveraged for all functions of the package, the following command line arguments were used:

![image](https://user-images.githubusercontent.com/7281657/104060199-8e6ed480-51c4-11eb-8c57-699e211ca8c3.png)

The "-threads" argument, when set to -1, uses the maximum number of threads available on the host machine. In PaDELPy, this value is set to -1 by default:

https://github.com/ECRL/PaDELPy/blob/fd09a3c29786b8374a43409951bb06bc3395d98e/padelpy/wrapper.py#L49

The "from_smiles" function, https://github.com/ECRL/PaDELPy/blob/fd09a3c29786b8374a43409951bb06bc3395d98e/padelpy/functions.py#L23 currently does not support multiple SMILES strings, and will not leverage multiprocessing/multithreading. I'm going to work on implementing support for supplying this function with multiple SMILES strings (i.e. a list of strings), which would allow PaDELPy to leverage multiprocessing/multithreading.

**Comment by tjkessler** [comment]
@katasanirohith,

This issue should be fixed with pull request https://github.com/ECRL/PaDELPy/pull/16. I'm going to close this issue, but feel free to open it again or submit a new one if you experience any issues!

Best,
Travis
