### ISSUE TITLE
Unexpected keyword argument 'usefilenamesasmolname'

### ISSUE THREAD

**Issue by mehr-licht** [ECRL/PaDELPy#17]
When trying to configure **usefilenamesasmolname** option:

```
from padelpy import padeldescriptor

padeldescriptor(usefilenamesasmolname=True)
```

I get the following error:

`TypeError: padeldescriptor() got an unexpected keyword argument 'usefilenamesasmolname'`

**Comment by tjkessler** [comment]
Fixed as of https://github.com/ECRL/PaDELPy/pull/18
