### ISSUE TITLE
Can not apply with .smi file (~4000 cps)

### ISSUE THREAD

**Issue by tieulongphan8995** [ECRL/PaDELPy#25]
I want to calculate molecular descriptor for more than 4000 cps in file.smi. However, when I use:

from padelpy import padeldescriptor
padeldescriptor(mol_dir='molecule.smi', d_file='descriptors.csv')

The output descriptors.csv have no values. Tell me how to solve this issue. Tks so much

**Comment by tjkessler** [comment]
Hi @tieulongphan8995,

When you use the 'padeldescriptor' function, you have to specify in the function call which descriptors you want to calculate:

```python
from padelpy import padeldescriptor

# Calculate 2-D descriptors
padeldescriptor(mol_dir='molecule.smi', d_file='descriptors.csv', d_2d=True)

# Calculate 3-D descriptors
padeldescriptor(mol_dir='molecule.smi', d_file='descriptors.csv', d_3d=True)

# Calculate 2-D and 3-D descriptors
padeldescriptor(mol_dir='molecule.smi', d_file='descriptors.csv', d_2d=True, d_3d=True)
```

If the 'd_2d' and 'd_3d' arguments are not specified, the output file will not be populated with descriptors.

Further, I highly suggest that you set 'retainorder' to 'True', this will ensure the descriptors in your output CSV file appear in the same order as the molecules in your input file:

```python
padeldescriptor(mol_dir='molecule.smi', d_file='descriptors.csv', d_2d=True, d_3d=True, retainorder=True)
```

Best,
Travis
