### ISSUE TITLE
padeldescriptor returns no output

### ISSUE THREAD

**Issue by naeemmrz** [ECRL/PaDELPy#26]
Hello, 

I've created a .smi file of smiles (1 smile in each row) and I'm running it as:

! pip install padelpy
from padelpy import padeldescriptor
padeldescriptor(mol_dir='ai_ml.smi', d_2d=True, d_3d=True, fingerprints=True, detectaromaticity=True, removesalt=True, retainorder=True, threads=2, d_file='ai_ml_padel_output.csv' )

It exits with no error, however, no output file is generated, any idea what I'm doing wrong? I'm running it on a Jupyter notebook and no errors occurred on installation.

**Comment by tjkessler** [comment]
Hi @naeemmrz,

I've tested your implementation, and it looks like the argument `detectaromaticity=True` is causing this issue. According to PaDEL-Descriptor's website, this argument doesn't play nice with other arguments, specifically 3-D descriptor generation: see http://www.yapcwsoft.com/dd/padeldescriptor/, "Known Problems" section.

Removing the `detectaromaticity` argument (letting it default to `False`) seems to work and produces an output file:

```python
from padelpy import padeldescriptor

padeldescriptor(
    mol_dir='ai_ml.smi',
    d_2d=True,
    d_3d=True,
    fingerprints=True,
    # detectaromaticity=True,
    removesalt=True,
    retainorder=True,
    threads=2,
    d_file='ai_ml_padel_output.csv'
)
```

Let me know if this works for you! I'll wait a few days before I close the issue.

-Travis
