### ISSUE TITLE
Padelpy generating fingerprints in random order

### ISSUE THREAD

**Issue by AnjaliSetiya** [ECRL/PaDELPy#41]
It has come to my notice that when we are calculating molecules descriptors of say 5 molecules, the fingerprints generated are in random order.
![Screenshot from 2022-11-21 18-11-20](https://user-images.githubusercontent.com/66523813/203058620-9b1ded15-aab9-4fa3-ac7d-afb091ce13d5.png)
You can see in the image, the order of molecule has changed randomly, can you please tell me ehy is this and what is the work around, I have 10000 molecules, I can't keep a track of any because of this.

**Comment by tjkessler** [comment]
Hi @AnjaliSetiya,

If you are using the "padeldescriptor" wrapper function, you need to supply "retainorder=True" to the function. Perhaps it would be more beneficial for me to set its default value to "True" instead of "False"...

Anyways, let me know if this helps!

-T

**Comment by AnjaliSetiya** [comment]
Hi @tjkessler 
Yes setting "retainorder=True" in the  "padeldescriptor" wrapper function helped. And yes it should be default set to True, because it makes more sense to get the fingerprints in the order of the input molecules, it saves a lot of trouble users can encounter.
