### ISSUE TITLE
wrapper conflict with parallel processing

### ISSUE THREAD

**Issue by pikakolendo02** [ECRL/PaDELPy#46]
my code:
```
def get_padel_descs(smiles):
    dummy = from_smiles("CC")
    try:
        desc = from_smiles(
            smiles,
            timeout=10,
            threads=1,
        )
    except Exception:
        desc = dummy.fromkeys(dummy)
        sys.stderr.write("convert failed: " + smiles)

    return pd.Series(desc)

desc_list = get_padel_descs("CC").keys()

%%time
swifter.set_defaults(
    npartitions=32,
    scheduler="threads",  # threads or processes
    force_parallel=True,
)
df1.loc[:, desc_list] = df1["SMILES"].swifter.apply(get_padel_descs)
```
randomly get error:
```
File ~/mambaforge/lib/python3.11/site-packages/padelpy/functions.py:121, in from_smiles(smiles, output_csv, descriptors, fingerprints, timeout, maxruntime, threads)
    118     rows = [row for row in reader]
    119 desc_file.close()
--> 121 remove("{}.smi".format(timestamp))
    122 if not save_csv:
    123     remove(output_csv)

FileNotFoundError: [Errno 2] No such file or directory: '20230507055855835.smi'
```
I think it is the timestamp problem, two files (in parallel) shared the same timestamp. A random number could be better.

**Comment by tjkessler** [comment]
Hi @pikakolendo02,

Nice find - I think you're right, two parallel processes that start their descriptor calculations at the same time will have the same timestamped file, so one process will finish and delete the file, and the other process throws this exception.

I'll keep this issue open until I (or someone else) makes a change to PaDELPy's source code. I imagine appending the process ID to the timestamp will result in a unique file for each process regardless of start time.

Travis

**Comment by pikakolendo02** [comment]
Hello @tjkessler ,
Thank you for reply.
I added a random number in the filename as a workaround. Please see my pull request.
I also noticed the wrapper create the temp .smi and .csv in the current folder. Could it be better that create the temp files in /tmp or something in the memory other than on the disk?
In bash I use `mktemp` to create a temporarily file with a randomized filename in /tmp. Is there anything like it in Python?

**Comment by pikakolendo02** [comment]
BTW I use dask for parallel computing now. It utilize all cpu cores and run much faster than `threads=-1`.
Swifter cannot utilize all cpu and is laggy somehow.

**Comment by tjkessler** [comment]
Request merged, I'll update the version and upload to PyPI.

Re; tempfile: I remember fooling around with temporary files a few years ago when I first started working on PaDELPy, and I remember opting for the current solution but I can't remember why. Another look is certainly warranted, if we can get tempfiles working that should (1) speed things up a bit, and (2) avoid disk write/read
