### ISSUE TITLE
padepy stops calculating descriptors from .smi files

### ISSUE THREAD

**Issue by totocotonio1** [ECRL/PaDELPy#49]
Hi

padepy stops calculating descriptors from .smi files, the problem is not related to an error of a smile string, it stops calculating anywhere in the smi file, it should be fixed

Thank you

**Comment by tjkessler** [comment]
Hi @totocotonio1,

Could you please provide a code snippet and a .smi file so I can help troubleshoot?

Best,
Travis

**Comment by totocotonio1** [comment]
Hi @tjkessler 

here is the script, 

` pip install padelpy

from padelpy import padeldescriptor

padeldescriptor(mol_dir='/content/drive/MyDrive/test/test1.smi', d_file='/content/drive/MyDrive/test/descriptors1.csv', fingerprints=True)`

to be noted that I am using google colab

I am generating the files in myDrive

Thank you


[test1.zip](https://github.com/ecrl/padelpy/files/12244632/test1.zip)

**Comment by tjkessler** [comment]
@totocotonio1,

I was able to generate the descriptors for your .smi file locally with everything located in the same directory:

```python
from padelpy import padeldescriptor

padeldescriptor(
    mol_dir='test1.smi',
    d_file='descriptors1.csv',
    fingerprints=True
)
```

I've attached a ZIP file containing your .smi file, the resulting `descriptors1.csv` file, and the notebook I used: [smiles_file_test.zip](https://github.com/ecrl/padelpy/files/12245666/smiles_file_test.zip)

I don't have too much experience with using PaDELPy in Google Colab, hopefully someone else can weigh in! Given that I was able to run everything locally, maybe the error is a file path issue...

Best,
Travis

**Comment by totocotonio1** [comment]
Hi @tjkessler 

Thank you very much for your help,

I will generate the descriptors locally
